-- Execute este arquivo no Supabase em SQL Editor > New query.

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  patient text not null,
  mode text not null check (mode in ('presencial', 'teleconsulta')),
  specialty text not null,
  professional text not null,
  unit text not null,
  date_iso date not null,
  time text not null,
  created_at timestamptz not null default now()
);

alter table public.appointments enable row level security;

revoke all on table public.appointments from anon;
grant select, insert, delete on table public.appointments to authenticated;
grant usage, select on sequence public.appointments_id_seq to authenticated;

drop policy if exists "Usuários veem suas próprias consultas" on public.appointments;
create policy "Usuários veem suas próprias consultas"
on public.appointments for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "Usuários criam suas próprias consultas" on public.appointments;
create policy "Usuários criam suas próprias consultas"
on public.appointments for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "Usuários cancelam suas próprias consultas" on public.appointments;
create policy "Usuários cancelam suas próprias consultas"
on public.appointments for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
