-- Agenda+ · schema de pacientes e médicos
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'patient' check (role in ('patient', 'doctor')),
  full_name text not null default '',
  crm text,
  crm_state char(2),
  specialty text,
  phone text,
  avatar_url text,
  clinic_name text not null default 'Atendimento profissional',
  clinic_address text not null default 'Local a confirmar',
  availability jsonb not null default jsonb_build_object(
    'monday', jsonb_build_object('enabled', true, 'start', '08:00', 'end', '18:00'),
    'tuesday', jsonb_build_object('enabled', true, 'start', '08:00', 'end', '18:00'),
    'wednesday', jsonb_build_object('enabled', true, 'start', '08:00', 'end', '18:00'),
    'thursday', jsonb_build_object('enabled', true, 'start', '08:00', 'end', '18:00'),
    'friday', jsonb_build_object('enabled', true, 'start', '08:00', 'end', '18:00'),
    'saturday', jsonb_build_object('enabled', false, 'start', '08:00', 'end', '12:00'),
    'sunday', jsonb_build_object('enabled', false, 'start', '08:00', 'end', '12:00')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  doctor_id uuid references public.profiles(user_id) on delete set null,
  patient text not null,
  mode text not null check (mode in ('presencial', 'teleconsulta')),
  specialty text not null,
  professional text not null,
  unit text not null,
  date_iso date not null,
  time text not null,
  status text not null default 'Confirmada',
  created_at timestamptz not null default now()
);

alter table public.appointments add column if not exists doctor_id uuid references public.profiles(user_id) on delete set null;
alter table public.appointments add column if not exists status text not null default 'Confirmada';

create index if not exists appointments_doctor_date_idx on public.appointments(doctor_id, date_iso, time);
create index if not exists profiles_role_specialty_idx on public.profiles(role, specialty);

create or replace function public.set_profile_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_profile_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  raw_role text := coalesce(new.raw_user_meta_data ->> 'role', 'patient');
begin
  if raw_role not in ('patient', 'doctor') then
    raw_role := 'patient';
  end if;

  insert into public.profiles (user_id, role, full_name, crm, crm_state, specialty, phone)
  values (
    new.id,
    raw_role,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.raw_user_meta_data ->> 'crm',
    new.raw_user_meta_data ->> 'crm_state',
    new.raw_user_meta_data ->> 'specialty',
    new.raw_user_meta_data ->> 'phone'
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();

-- Cria perfis para contas antigas que ainda não tenham uma linha em profiles.
insert into public.profiles (user_id, role, full_name, crm, crm_state, specialty, phone)
select
  id,
  case when raw_user_meta_data ->> 'role' = 'doctor' then 'doctor' else 'patient' end,
  coalesce(raw_user_meta_data ->> 'full_name', ''),
  raw_user_meta_data ->> 'crm',
  raw_user_meta_data ->> 'crm_state',
  raw_user_meta_data ->> 'specialty',
  raw_user_meta_data ->> 'phone'
from auth.users
on conflict (user_id) do nothing;

alter table public.profiles enable row level security;
revoke all on table public.profiles from anon;
grant select, insert, update on table public.profiles to authenticated;

drop policy if exists "Usuários veem seu próprio perfil e médicos públicos" on public.profiles;
create policy "Usuários veem seu próprio perfil e médicos públicos"
on public.profiles for select
to authenticated
using ((select auth.uid()) = user_id or role = 'doctor');

drop policy if exists "Usuários criam seu próprio perfil" on public.profiles;
create policy "Usuários criam seu próprio perfil"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Usuários atualizam seu próprio perfil" on public.profiles;
create policy "Usuários atualizam seu próprio perfil"
on public.profiles for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

alter table public.appointments enable row level security;
revoke all on table public.appointments from anon;
grant select, insert, delete on table public.appointments to authenticated;
grant usage, select on sequence public.appointments_id_seq to authenticated;

drop policy if exists "Usuários veem suas próprias consultas" on public.appointments;
drop policy if exists "Usuários e médicos veem suas consultas" on public.appointments;
create policy "Usuários e médicos veem suas consultas"
on public.appointments for select
to authenticated
using (
  (select auth.uid()) is not null
  and ((select auth.uid()) = user_id or (select auth.uid()) = doctor_id)
);
drop policy if exists "Usuários criam suas próprias consultas" on public.appointments;
create policy "Usuários criam suas próprias consultas"
on public.appointments for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and (
    doctor_id is null
    or exists (
      select 1 from public.profiles
      where profiles.user_id = doctor_id and profiles.role = 'doctor'
    )
  )
);

drop policy if exists "Usuários cancelam suas próprias consultas" on public.appointments;
create policy "Usuários cancelam suas próprias consultas"
on public.appointments for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

-- Bucket público apenas para leitura das fotos de perfil; cada médico só escreve na própria pasta.
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "Avatars públicos" on storage.objects;
create policy "Avatars públicos"
on storage.objects for select
to public
using (bucket_id = 'avatars');

drop policy if exists "Médicos enviam a própria foto" on storage.objects;
create policy "Médicos enviam a própria foto"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
  and exists (
    select 1 from public.profiles
    where profiles.user_id = (select auth.uid()) and profiles.role = 'doctor'
  )
);

drop policy if exists "Médicos atualizam a própria foto" on storage.objects;
create policy "Médicos atualizam a própria foto"
on storage.objects for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);
